steps:
  # -----------------------------------------------------------------------------
  # Build and Push Web App
  # -----------------------------------------------------------------------------
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Prepare Web env'
    entrypoint: bash
    args:
      - -c
      - |
        set -euo pipefail
        mkdir -p apps/web
        get_secret_or_value() {
          VAL="$$1"
          # Treat values that look like secret references (projects/... or contain ':') as secrets.
          if [[ "$$VAL" == projects/* || "$$VAL" == *:* ]]; then
            # Normalize colon form 'projects/.../secrets/NAME:latest' -> 'projects/.../secrets/NAME/versions/latest'
            SECRET_RES="$$VAL"
            if [[ "$$SECRET_RES" == *:* ]]; then
              SECRET_RES="$${SECRET_RES/:/\/versions/}"
            fi
            # If no /versions/ present, append latest
            if [[ "$$SECRET_RES" != */versions/* ]]; then
              SECRET_RES="$$SECRET_RES/versions/latest"
            fi
            # Try to read secret; capture output. Use clean quoting for gcloud.
            SECRET_VALUE="$(gcloud secrets versions access \"${SECRET_RES}\" --project=\"${PROJECT_ID}\" 2>/dev/null || true)"
            # If gcloud failed (empty), try fallback: if VAL contains literal JSON (starts with '{'), echo VAL
            if [[ -z "$$SECRET_VALUE" ]]; then
              # If VAL looks like inline JSON (starts with '{'), return it; otherwise return empty string
              if [[ "$$VAL" == \{* ]]; then
                echo "$$VAL"
              else
                echo ""
              fi
            else
              echo "$$SECRET_VALUE"
            fi
          else
            # Otherwise treat as literal value
            echo "$$VAL"
          fi
        }
        echo "Writing apps/web/.env with secrets/values (kept out of image)"
        echo -n > apps/web/.env
        echo "NEXT_PUBLIC_FIREBASE_CONFIG=$(get_secret_or_value \"$_NEXT_PUBLIC_FIREBASE_CONFIG\")" >> apps/web/.env
        echo "NEXTAUTH_SECRET=$(get_secret_or_value \"$_SECRET_NEXTAUTH_SECRET\")" >> apps/web/.env
        echo "DATABASE_URL=$(get_secret_or_value \"$_SECRET_DATABASE_URL\")" >> apps/web/.env
        echo "GCS_BUCKET_NAME=$_GCS_BUCKET_NAME" >> apps/web/.env
        echo "CLOUD_SQL_INSTANCE_CONNECTION_NAME=$_CLOUD_SQL_INSTANCE_CONNECTION_NAME" >> apps/web/.env
        echo "FIREBASE_SERVICE_ACCOUNT_JSON=$(get_secret_or_value \"$_SECRET_FIREBASE_SA\")" >> apps/web/.env

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Web'
    args:
      - 'build'
      - '--tag=$_GCP_REGION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REGISTRY_REPO/$_SERVICE_NAME_WEB:$COMMIT_SHA'
      - '--file=Dockerfile'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Web'
    args:
      - 'push'
      - '$_GCP_REGION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REGISTRY_REPO/$_SERVICE_NAME_WEB:$COMMIT_SHA'

  # -----------------------------------------------------------------------------
  # Deploy Web App to Cloud Run
  # -----------------------------------------------------------------------------
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy Web'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '$_SERVICE_NAME_WEB'
      - '--image=$_GCP_REGION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REGISTRY_REPO/$_SERVICE_NAME_WEB:$COMMIT_SHA'
      - '--region'
      - '$_GCP_REGION'
      - '--platform'
      - 'managed'
      - '--quiet'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances=$_CLOUD_SQL_INSTANCE_CONNECTION_NAME'
      # --- 環境変数 / シークレットの自動注入（Cloud Build トリガーで置換変数を設定してください） ---
      # 非機密（公開可）な値は --update-env-vars で渡します（置換変数をトリガーに設定）
      - '--update-env-vars=CLOUD_SQL_INSTANCE_CONNECTION_NAME=$_CLOUD_SQL_INSTANCE_CONNECTION_NAME'
      # 機密は Secret Manager を使い --set-secrets で注入します。トリガー側で _SECRET_* を設定してください。
      # 例: _SECRET_FIREBASE_SA => projects/PROJECT_ID/secrets/FIREBASE_SA:latest
      - '--set-secrets=NEXTAUTH_URL=$_NEXTAUTH_URL,NEXTAUTH_SECRET=$_SECRET_NEXTAUTH_SECRET,GCS_BUCKET_NAME=$_GCS_BUCKET_NAME,FIREBASE_SERVICE_ACCOUNT_JSON=$_SECRET_FIREBASE_SA,NEXT_PUBLIC_FIREBASE_CONFIG=$_NEXT_PUBLIC_FIREBASE_CONFIG,DATABASE_URL=$_SECRET_DATABASE_URL'
      # --- 必要に応じて追加のオプション ---
      # - '--service-account=your-service-account@your-project.iam.gserviceaccount.com'
      # - '--update-env-vars=KEY1=VALUE1,KEY2=VALUE2'
      # - '--set-secrets=OTHER=projects/PROJECT_ID/secrets/OTHER:latest'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Make Web Public'
    entrypoint: gcloud
    args:
      - 'run'
      - 'services'
      - 'add-iam-policy-binding'
      - '$_SERVICE_NAME_WEB'
      - '--region=$_GCP_REGION'
      - '--member=allUsers'
      - '--role=roles/run.invoker'

  # -----------------------------------------------------------------------------
  # Build and Push Worker
  # -----------------------------------------------------------------------------
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Worker'
    args:
      - 'build'
      - '--tag=$_GCP_REGION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REGISTRY_REPO/$_SERVICE_NAME_WORKER:$COMMIT_SHA'
      - '--file=docker/worker.prod.Dockerfile'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Worker'
    args:
      - 'push'
      - '$_GCP_REGION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REGISTRY_REPO/$_SERVICE_NAME_WORKER:$COMMIT_SHA'

  # -----------------------------------------------------------------------------
  # Deploy Worker to Cloud Run
  # -----------------------------------------------------------------------------
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy Worker'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '$_SERVICE_NAME_WORKER'
      - '--image=$_GCP_REGION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REGISTRY_REPO/$_SERVICE_NAME_WORKER:$COMMIT_SHA'
      - '--region'
      - '$_GCP_REGION'
      - '--platform'
      - 'managed'
      - '--quiet'
      - '--no-allow-unauthenticated' # Pub/Subからの呼び出しのみ許可
      - '--add-cloudsql-instances=$_CLOUD_SQL_INSTANCE_CONNECTION_NAME'
      # --- 必要に応じて以下のオプションを有効化してください ---
      # - '--service-account=your-service-account@your-project.iam.gserviceaccount.com'
      # - '--update-env-vars=KEY1=VALUE1,KEY2=VALUE2'
      # - '--set-secrets=SECRET_NAME=secret-name:latest'

images:
  - '$_GCP_REGION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REGISTRY_REPO/$_SERVICE_NAME_WEB:$COMMIT_SHA'
  - '$_GCP_REGION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REGISTRY_REPO/$_SERVICE_NAME_WORKER:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
# -------------------------------------------------------------------------------
# 置換変数 (Cloud Build トリガーで設定)
# -------------------------------------------------------------------------------
# _GCP_REGION: GCPリージョン (例: asia-northeast1)
# _ARTIFACT_REGISTRY_REPO: Artifact Registry のリポジトリ名
# _SERVICE_NAME_WEB: WebアプリのCloud Runサービス名
# _SERVICE_NAME_WORKER: WorkerのCloud Runサービス名
# _CLOUD_SQL_INSTANCE_CONNECTION_NAME: Cloud SQL の接続名
# -------------------------------------------------------------------------------
