steps:
  # -----------------------------------------------------------------------------
  # Build and Push Web App
  # -----------------------------------------------------------------------------
  # Firebaseのサービスアカウントキーをファイルとして保存する
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Prepare Firebase Service Account Key'
    entrypoint: 'bash'
    args:
      - '-c'
      # 実行前に変数が空でないかチェックし、エラーメッセージを明確にする
      - |
        if [ -z "$$_SECRET_FIREBASE_SA" ]; then
          echo "ERROR: The substitution variable '_SECRET_FIREBASE_SA' is not set."
          echo "Please check the Cloud Build trigger configuration."
          exit 1
        fi
        gcloud secrets versions access "$${_SECRET_FIREBASE_SA}/versions/latest" > firebase-sa-key.json

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Web'
    # secretEnvでビルドステップの環境変数を設定
    secretEnv:
      - 'NEXT_PUBLIC_FIREBASE_CONFIG'
      - 'NEXTAUTH_SECRET'
      - 'DATABASE_URL'
    args:
      - 'build'
      - '--tag=$_GCP_REGION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REGISTRY_REPO/$_SERVICE_NAME_WEB:$COMMIT_SHA'
      - '--file=Dockerfile'
      # --build-arg を使ってDockerビルド内部に環境変数を渡す
      - '--build-arg=NEXT_PUBLIC_FIREBASE_CONFIG'
      - '--build-arg=NEXTAUTH_SECRET'
      - '--build-arg=DATABASE_URL'
      - '--build-arg=GCS_BUCKET_NAME=$_GCS_BUCKET_NAME' # シークレットでない値も同様に渡せる
      - '--build-arg=CLOUD_SQL_INSTANCE_CONNECTION_NAME=$_CLOUD_SQL_INSTANCE_CONNECTION_NAME'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Web'
    args:
      - 'push'
      - '$_GCP_REGION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REGISTRY_REPO/$_SERVICE_NAME_WEB:$COMMIT_SHA'

  # -----------------------------------------------------------------------------
  # Deploy Web App to Cloud Run
  # -----------------------------------------------------------------------------
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy Web'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '$_SERVICE_NAME_WEB'
      - '--image=$_GCP_REGION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REGISTRY_REPO/$_SERVICE_NAME_WEB:$COMMIT_SHA'
      - '--region'
      - '$_GCP_REGION'
      - '--platform'
      - 'managed'
      - '--quiet'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances=$_CLOUD_SQL_INSTANCE_CONNECTION_NAME'
      # --- 環境変数 / シークレットの自動注入（Cloud Build トリガーで置換変数を設定してください） ---
      # 非機密（公開可）な値は --update-env-vars で渡します（置換変数をトリガーに設定）
      - '--update-env-vars=CLOUD_SQL_INSTANCE_CONNECTION_NAME=$_CLOUD_SQL_INSTANCE_CONNECTION_NAME'
      # 機密は Secret Manager を使い --set-secrets で注入します。トリガー側で _SECRET_* を設定してください。
      # 例: _SECRET_FIREBASE_SA => projects/PROJECT_ID/secrets/FIREBASE_SA:latest
      - '--set-secrets=NEXTAUTH_URL=$_NEXTAUTH_URL,NEXTAUTH_SECRET=$_SECRET_NEXTAUTH_SECRET,GCS_BUCKET_NAME=$_GCS_BUCKET_NAME,FIREBASE_SERVICE_ACCOUNT_JSON=$_SECRET_FIREBASE_SA,NEXT_PUBLIC_FIREBASE_CONFIG=$_NEXT_PUBLIC_FIREBASE_CONFIG,DATABASE_URL=$_SECRET_DATABASE_URL'
      # --- 必要に応じて追加のオプション ---
      # - '--service-account=your-service-account@your-project.iam.gserviceaccount.com'
      # - '--update-env-vars=KEY1=VALUE1,KEY2=VALUE2'
      # - '--set-secrets=OTHER=projects/PROJECT_ID/secrets/OTHER:latest'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Make Web Public'
    entrypoint: gcloud
    args:
      - 'run'
      - 'services'
      - 'add-iam-policy-binding'
      - '$_SERVICE_NAME_WEB'
      - '--region=$_GCP_REGION'
      - '--member=allUsers'
      - '--role=roles/run.invoker'

  # -----------------------------------------------------------------------------
  # Build and Push Worker
  # -----------------------------------------------------------------------------
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Worker'
    args:
      - 'build'
      - '--tag=$_GCP_REGION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REGISTRY_REPO/$_SERVICE_NAME_WORKER:$COMMIT_SHA'
      - '--file=docker/worker.prod.Dockerfile'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Worker'
    args:
      - 'push'
      - '$_GCP_REGION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REGISTRY_REPO/$_SERVICE_NAME_WORKER:$COMMIT_SHA'

  # -----------------------------------------------------------------------------
  # Deploy Worker to Cloud Run
  # -----------------------------------------------------------------------------
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy Worker'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '$_SERVICE_NAME_WORKER'
      - '--image=$_GCP_REGION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REGISTRY_REPO/$_SERVICE_NAME_WORKER:$COMMIT_SHA'
      - '--region'
      - '$_GCP_REGION'
      - '--platform'
      - 'managed'
      - '--quiet'
      - '--no-allow-unauthenticated' # Pub/Subからの呼び出しのみ許可
      - '--add-cloudsql-instances=$_CLOUD_SQL_INSTANCE_CONNECTION_NAME'
      # --- 必要に応じて以下のオプションを有効化してください ---
      # - '--service-account=your-service-account@your-project.iam.gserviceaccount.com'
      # - '--update-env-vars=KEY1=VALUE1,KEY2=VALUE2'
      # - '--set-secrets=SECRET_NAME=secret-name:latest'

images:
  - '$_GCP_REGION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REGISTRY_REPO/$_SERVICE_NAME_WEB:$COMMIT_SHA'
  - '$_GCP_REGION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REGISTRY_REPO/$_SERVICE_NAME_WORKER:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY

# このビルドで利用するシークレットを宣言する
availableSecrets:
  secretManager:
    # versionName の末尾に /versions/latest を追加
    # NEXT_PUBLIC_FIREBASE_CONFIG
    - versionName: ${_NEXT_PUBLIC_FIREBASE_CONFIG}/versions/latest
      env: 'NEXT_PUBLIC_FIREBASE_CONFIG'
    # NEXTAUTH_SECRET
    - versionName: ${_SECRET_NEXTAUTH_SECRET}/versions/latest
      env: 'NEXTAUTH_SECRET'
    # DATABASE_URL
    - versionName: ${_SECRET_DATABASE_URL}/versions/latest
      env: 'DATABASE_URL'
